In [231]:
import pandas as pd
import numpy as np
import re
import json
import pickle
# from sklearn.cluster import KMeans
from sklearn.feature_extraction.text import TfidfVectorizer
from sklearn.metrics.pairwise import cosine_similarity


df = pd.read_csv('dataml.csv',sep=';')
df

,Name,Nama Panggil,Jenis Kelamin,Jurusan,Angkatan,Divisi,Status,Banyak Project,Skill
0,Muhammad Zidan Fadhilah,Zidan,Laki-laki,Teknik Telekomunikasi,2019,Cyber Security,Asisten Lab,6,Pwning
1,Muhammad Zidan Fadhilah,Zidan,Laki-laki,Teknik Telekomunikasi,2019,Cyber Security,Asisten Lab,6,Git
2,Muhammad Zidan Fadhilah,Zidan,Laki-laki,Teknik Telekomunikasi,2019,Cyber Security,Asisten Lab,6,Cryptography
3,Muhammad Zidan Fadhilah,Zidan,Laki-laki,Teknik Telekomunikasi,2019,Cyber Security,Asisten Lab,6,Reverse Engineering
4,Muhammad Azriel,Azriel,Laki-laki,Teknik Telekomunikasi,2019,GIS,Asisten Lab,6,Figma
...,...,...,...,...,...,...,...,...,...
172,Yulintyandra Puja Antanita,Yulin,Perempuan,Teknik Telekomunikasi,2021,GIS,Calon Asisten,8,Blender
173,Yulintyandra Puja Antanita,Yulin,Perempuan,Teknik Telekomunikasi,2021,GIS,Calon Asisten,8,Unity
174,Yulintyandra Puja Antanita,Yulin,Perempuan,Teknik Telekomunikasi,2021,GIS,Calon Asisten,8,C
175,Malvin Nugraha,Malvin,Laki-laki,Teknik Telekomunikasi,2021,GIS,Calon Asisten,10,Blender
176,Malvin Nugraha,Malvin,Laki-laki,Teknik Telekomunikasi,2021,GIS,Calon Asisten,10,Unity

In [232]:
data = pd.DataFrame(df, columns=['Name', 'Divisi', 'Skill'])
data

                           Name          Divisi                Skill
0       Muhammad Zidan Fadhilah  Cyber Security               Pwning
1       Muhammad Zidan Fadhilah  Cyber Security                  Git
2       Muhammad Zidan Fadhilah  Cyber Security         Cryptography
3       Muhammad Zidan Fadhilah  Cyber Security  Reverse Engineering
4               Muhammad Azriel             GIS                Figma
..                          ...             ...                  ...
172  Yulintyandra Puja Antanita             GIS              Blender
173  Yulintyandra Puja Antanita             GIS                Unity
174  Yulintyandra Puja Antanita             GIS                    C
175              Malvin Nugraha             GIS              Blender
176              Malvin Nugraha             GIS                Unity

[177 rows x 3 columns]

In [233]:
data['Skill'] = data['Skill'].str.lower()
data

                           Name          Divisi                Skill
0       Muhammad Zidan Fadhilah  Cyber Security               pwning
1       Muhammad Zidan Fadhilah  Cyber Security                  git
2       Muhammad Zidan Fadhilah  Cyber Security         cryptography
3       Muhammad Zidan Fadhilah  Cyber Security  reverse engineering
4               Muhammad Azriel             GIS                figma
..                          ...             ...                  ...
172  Yulintyandra Puja Antanita             GIS              blender
173  Yulintyandra Puja Antanita             GIS                unity
174  Yulintyandra Puja Antanita             GIS                    c
175              Malvin Nugraha             GIS              blender
176              Malvin Nugraha             GIS                unity

[177 rows x 3 columns]

In [234]:
data = data[data['Skill'].str.len() > 0]
data.to_json('skill.json')
data

                           Name          Divisi                Skill
0       Muhammad Zidan Fadhilah  Cyber Security               pwning
1       Muhammad Zidan Fadhilah  Cyber Security                  git
2       Muhammad Zidan Fadhilah  Cyber Security         cryptography
3       Muhammad Zidan Fadhilah  Cyber Security  reverse engineering
4               Muhammad Azriel             GIS                figma
..                          ...             ...                  ...
172  Yulintyandra Puja Antanita             GIS              blender
173  Yulintyandra Puja Antanita             GIS                unity
174  Yulintyandra Puja Antanita             GIS                    c
175              Malvin Nugraha             GIS              blender
176              Malvin Nugraha             GIS                unity

[177 rows x 3 columns]

In [235]:
vectorizer = TfidfVectorizer(
    analyzer='word', 
    sublinear_tf=True,
    strip_accents='unicode',
    token_pattern=r'\w{1,}',
    ngram_range=(1, 1),
    max_features=10000)
tfidf = vectorizer.fit_transform(data['Skill'])

In [248]:
def search (query, vectorizer):
    query = 'tensorflow'
    processed = re.sub("[^a-zA-Z0-9]", "", query.lower())
    query_vec = vectorizer.transform([processed])
    similarity = cosine_similarity(query_vec, tfidf).flatten()
    indices = np.argpartition(similarity, -10)[-10:]
    result = data.iloc[indices]
    # result = result.sort_values('')
    return result

In [249]:
search('tensorflow', vectorizer)

                           Name          Divisi            Skill
60   Rafi Andhika Putra Pratama        Big Data               ml
62    Nasrullah Pandu Dewantara  Cyber Security              git
61    Nasrullah Pandu Dewantara  Cyber Security           python
55      Muhammad Hilmi Izzulhaq        Big Data          blender
142                  Satya Adhi  Cyber Security       tensorflow
39            Dias Daffa Wiwaha        Big Data       tensorflow
58   Rafi Andhika Putra Pratama        Big Data           python
57      Muhammad Hilmi Izzulhaq        Big Data  adobe photoshop
56      Muhammad Hilmi Izzulhaq        Big Data    adobe premier
43      Retno Fauziah Istiqomah        Big Data       tensorflow

In [238]:
with open('listdata.pkl','wb') as a:
    pickle.dump(data, a)

In [239]:
with open('listdata.pkl','rb') as a:
    magen = pickle.load(a)
magen

                           Name          Divisi                Skill
0       Muhammad Zidan Fadhilah  Cyber Security               pwning
1       Muhammad Zidan Fadhilah  Cyber Security                  git
2       Muhammad Zidan Fadhilah  Cyber Security         cryptography
3       Muhammad Zidan Fadhilah  Cyber Security  reverse engineering
4               Muhammad Azriel             GIS                figma
..                          ...             ...                  ...
172  Yulintyandra Puja Antanita             GIS              blender
173  Yulintyandra Puja Antanita             GIS                unity
174  Yulintyandra Puja Antanita             GIS                    c
175              Malvin Nugraha             GIS              blender
176              Malvin Nugraha             GIS                unity

[177 rows x 3 columns]

In [240]:
with open('listkskill.pkl','wb') as b:
    pickle.dump(tfidf, b)

In [241]:
with open('listkskill.pkl','rb') as b:
    read = pickle.load(b)
read

<177x40 sparse matrix of type '<class 'numpy.float64'>'
	with 205 stored elements in Compressed Sparse Row format>